### ISSUE TITLE
"inbreed:NO means base population must have hets!"

### ISSUE THREAD

**Issue by Agenetics** [bodkan/admixr#88] opened 2022-08-16 14:19 UTC
Im trying to run qpAdm_rotation() for a singleton sample as target. Accordingly, inbreed:NO is set in the params. The candidates list is of 10 populations and the first population is Mbuti.DG, which has multiple samples under the label.

But I get this error.
"fatalx:
inbreed:NO means base population must have hets!"

What am I doing wrong? Is there a way in which the base population (like Mbuti.DG) doesnt go in as a source and remains as First outgroup?

**Comment by bodkan** [comment] 2022-08-17 11:53
Hello, 

this error:

> fatalx:
> inbreed:NO means base population must have hets!

comes from ADMIXTOOLS, not from admixr itself. I suggest you sent the same query to their [GitHub issues](https://github.com/DReichLab/AdmixTools/issues) and ask for advice there. My advice would be to first start with a qpAdm run without the rotation, to narrow down exactly which combination of populations gives this error. That way, the ADMIXTOOLS team will know exactly what's going on. This is because admixr doesn't do anything on top of what ADMIXTOOLS does, so the issue originates there.

Because the only thing admixr does is prepare configuration files for ADMIXTOOLS under the hood, if something needs to be tweaked in admixr, we can then follow up here (in case ADMIXTOOLS needs some parameter value to be changed, for instance).

I'm hesitant to give advice on ADMIXTOOLS-specific errors because I don't want to lead you to a dead-end. So generally if users have an ADMIXTOOLS problem, it's safer to ask there, and leave this issue tracker for admixr-specific bugs.

**Comment by Agenetics** [comment] 2022-08-17 12:56
Thank you.

Yes, the issue is identified. It comes when inbreed:NO is used but first population in the qpfstats population list is not a true diploid.
So I am assuming that when using qpAdm_rotate() in admixr, when the population list for qpfstats is made, it doesnt have Mbuti.DG as the base population (even though I have provided it first in the candidates list).

Using qpfstats directly on the same list of populations (in same order as given in candidate list, with the target added to the list) does not produce the error. So I think that admixr is somehow changing the order of the populations provided in candidatelist when it makes the poplist for qpfstats.

The possible solution from your end might be to ensure that the first population in the candidates list be used to compute qpfstats?

Hope I'm able to relay the problem clearly.

reference: README.qpfstats from admixtools github
"If inbreed: NO the base population (first in poplistname) MUST be a true diploid.   "

Thanks.

**Comment by bodkan** [comment] 2022-08-18 20:51
Thanks for the additional detail!

_admixr_ does not operate with qpfstats directly. In fact, the package predates qpfstats' existence, even (qpfstats is a relatively recent addition to ADMIXTOOLS).

Whatever is involved in the qpfstats interaction with qpAdm must come from qpAdm itself and the way it uses qpfstats internally. This is because _admixr_ never calls qpfstats in its codebase.

I'm a little out of my depth when it comes to the recent updates to ADMIXTOOLS and qpfstats in particular but I could definitely see the possibility that _admixr_ is doing something suboptimal here.

Is there a small reproducible example you could show which would include a small bit of data that would clearly demonstrate and reproduce the problem? I'm using qpAdm very rarely in my current job so getting a concrete reproducible bugreport would really help.

As for admixr changing the order of populations, if you take a look at the `qpAdm_rotation` code, the function tests all possible combinations of candidates: https://github.com/bodkan/admixr/blob/c823d4ea7d824f63407642eaa089b0e964fbd65f/R/qpAdm.R#L44 Not sure what _"ensure that the first population in the candidates list be used to compute qpfstats"_ should do in this context.

Again, please note that I have never worked with qpfstats directly. But I will try to take a closer look at the problem (having that concrete data example would really help here). If this is considered a bug, then of course this should be fixed somehow.

**Comment by Agenetics** [comment] 2022-08-19 03:29
Right. I understand the issue now.

So to reproduce the problem, 
1. use any singleton label (with 1 sample only) as Target. Eg. in my case 'Rakhigarhi'.  Candidate list has all .DG labels. eg (Mbuti.DG, Karitiana.DG. Irula.DG, Papuan.DG, Dai.DG). qpAdm_rotate works perfectly in this case. I used nsources=2.
![image](https://user-images.githubusercontent.com/57030047/185534625-64458ba9-c083-4204-a166-fd69c513f794.png)
2. But if with same setting, candidate list has only one .DG label, then it fails. example. Mbuti.DG, Russia_Khvalynsk_Eneolithic, EHG, Russia_Samara_EBA_Yamnaya, Germany_EN_LBK 
![image](https://user-images.githubusercontent.com/57030047/185534848-3575095a-b6fe-4f2d-be38-a1a9dd71186b.png)

qpfstats only needs geno/snp/ind files as input, along with a file containing list of populations. then qpfstats output is used as input for qpAdm (instead of geno files. parqpadm file has 2 options for input: geno files directly or qpfstats output file and left/right pops need to be a part of this qpfstats list). The advantage offered is that qpfstats can be run just once, and later qpAdm steps take only few seconds, and multiple models can be tested very fast.

So I think this is what is happening. Your program calls qpAdm nCr times. n being no of candidates and r being no. of sources.
Each time qpAdm is called, qpAdm collates the left and right pops provided by admixr (it appends left pops AFTER right)  in one file and passes it to qpfstats. The output is passed back to qpAdm. This process is repeated nCr times.

So when the only .DG population is in the left being tested as source, there is no .DG pop in the right and qpfstats fails as the .DG label is no longer first in the list it gets as input.

The solution to this seems to be either of

1. whenever admixr provides left and right file to qpAdm, it must ensure there is a .DG population as 1st in the right pops file (especially when inbreed: NO which is forced when there's a singleton label used).
2. Or that admixr can ask for an outgroup explicitly, and insert it into 1st line of each right pop file.
3. Best solution imo, is for admixr to use qpfstats once on the whole (candidates + target) list. And only use qpfstats output as input for all subsequent qpAdm rotating models. This will probably reduce run time by 95% or more.

**Comment by bodkan** [comment] 2022-08-24 13:56
Amazing debugging summary, thank you so much! I wish all feature requests or bug reports were this detailed. :)

I tend to agree with you in that option # 3 is probably best. _admixr_ currently doesn't use qpfstats (in fact, it doesn't contain a wrapper for that binary) because the package predates its existence. I wasn't aware that recent versions of ADMIXTOOLS use qpfstats internally in qpAdm (I assumed qpfstats is entirely optional).

I'm afraid I won't have time to implement this over the next couple of weeks but I have recently closed many opened _admixr_ issues in a push to release the 1.0 version to CRAN, so it makes sense to implement/fix this before I do this.

I will have to think about how to include qpfstats though. Maybe the `eigenstrat()` function could have an option to pre-calculate qpfstats, which would then be tracked together with the rest of the data and passed to each wrapper. I would have to read up on internal qpfstats use though, as I would expect other functions can use this as well, so maybe different functions could have a `use_qpfstats = <TRUE|FALSE>` argument or something.

In the meantime, before I do this, maybe you could copy `qpAdm_rotate()` and implement a work around that you suggested under # 1 or # 2. This will not be as fast as # 3 but it will get around the annoying issue of ADMIXTOOLS crashing with an error.


Again, many many many thanks for reporting this and for explaining what's going on under the hood!

**Comment by Agenetics** [comment] 2022-08-24 15:49
Thanks for the kind words.

> I wasn't aware that recent versions of ADMIXTOOLS use qpfstats internally in qpAdm 

Yes, I figured it out while checking the processes table. when running qpAdm, qpfstats is run first, then qpAdm again.

> I will have to think about how to include qpfstats though. Maybe the eigenstrat() function could have an option to pre-calculate qpfstats, which would then be tracked together with the rest of the data and passed to each wrapper. I would have to read up on internal qpfstats use though, as I would expect other functions can use this as well, so maybe different functions could have a use_qpfstats = <TRUE|FALSE> argument or something.

I wouldn't run qpfstats on more than 30-35 labels because of time taken (I use 25 max, but time taken depends on system used). So if you do included qpfstats=true option in eigenstrat(), I would suggest that you ask the user to provide a subset list explicitly, only for labels which will be useful to the user.

As such, qpfstats is very simple, you provide as parameters genp/snp/ind file location, population list file name, output file name and similar parameters (allsnps, inbreed etc). and you get an output file. This output file can replace .geno/snp/ind in subsequent qpAdm/qpGraph runs. I suspect it will work for qpwave too, though I have never used it.

> In the meantime, before I do this, maybe you could copy qpAdm_rotate() and implement a work around that you suggested under # 1 or # 2. 

Thanks, I will try to work something.

**Closed as completed** 2022-08-24 16:14 UTC

**Comment by Agenetics** [comment] 2022-08-24 16:58
I have done a workaround which suits me.
edited the qpAdm_rotation() function with
` trace("qpAdm_rotation",edit=TRUE)`

Then, changed this line
`outgroups <- setdiff(candidates, sources[i, ])`

to

`outgroups <- setdiff(append("Mbuti.DG", candidates), sources[i, ])`

This forcefully appends Mbuti.DG before all other combinations of right pops. And then, Mbuti.DG shouldn't be present in the user defined candidates list.

I have verified that it works (at least it does with minimize: FALSE) with no errors. No .DG label required in candidates list as I am appending Mbuti.DG as first forcefully to all right pops lists.

![image](https://user-images.githubusercontent.com/57030047/186478225-e018e992-1e66-4b27-976d-0e31f6656fb6.png)

**Comment by bodkan** [comment] 2022-08-24 19:07
Super! 👏 Glad to hear you've found a workaround so quickly.

> I wouldn't run qpfstats on more than 30-35 labels because of time taken (I use 25 max, but time taken depends on system used). So if you do included qpfstats=true option in eigenstrat(), I would suggest that you ask the user to provide a subset list explicitly, only for labels which will be useful to the user.
> 
> As such, qpfstats is very simple, you provide as parameters genp/snp/ind file location, population list file name, output file name and similar parameters (allsnps, inbreed etc). and you get an output file. This output file can replace .geno/snp/ind in subsequent qpAdm/qpGraph runs. I suspect it will work for qpwave too, though I have never used it.

Ah, OK. Good to know. Thanks for the explanation.

It sounds like I really should first read the new documentation to first learn in detail what are the limits. And also, what other tools in ADMIXTOOLS can use this (and how). At the very least, perhaps a solution could be implemented for `qpAdm()`  itself, rather than including it "upstream" in `eigenstrat()`.

Will do some more thinking when I have more bandwith and maybe ping here for feedback.

Again, thanks for you help and good luck with your analyses!
