### ISSUE TITLE
qpAdm_rotation problem when nsources >= 3

### ISSUE THREAD

**Issue by paikusuma** [bodkan/admixr#77] opened 2020-10-17 09:46 UTC
Hi!

Thanks for this nice package!
I have a question about the `qpAdm_rotation`.

I've run that on `nsources == 2` and all is well. But whenever I run `nsources >= 3`, it gave me an error.
Here's the error I got when I run `nsources == 3`:
`Error in $<-.data.frame(*tmp*, "model", value = c("m1", "m1", "m1", :  replacement has 600 rows, data has 840`

I am not sure what is wrong.

Secondly, I checked in the `qpAdm.R`, in line 71 and 72 (renaming sources and stderr columns) to merge proportion tables:
`names(result$proportions)[2:(1 + nsources)] <- paste0("prop", 1:nsources)`
`names(result$proportions)[4:(3 + nsources)] <- paste0("stderr", 1:nsources)`

For `nsources == 2`, there you rename column 2-3 for prop and 4-5 for stderr. However when `nsources == 3`, the 4th column of `result$proportions` is now the 3rd population source's proportion. The overlap can cause a problem, I guess? But I am not sure that it's related to the first problem I encounter above.

Thanks a lot!

+Pai

**Comment by paikusuma** [comment] 2020-10-17 13:19
I checked line by line on `qpAdm_rotation`, and I found the source of the problem that produces the error I mentioned above.
It's on the line 111 of `qpAdm.R`: 
`subsets$model <- sort(rep(models, 1 + 2^(nsources - 1)))`

also perhaps a fix on line 72:
 `names(result$proportions)[(2 + nsources):(2 * nsources + 1)] <- paste0("stderr", 1:nsources)` ?

**Comment by bodkan** [comment] 2020-10-19 17:34
Hello @paikusuma,

Thank you for trying out the new `qpAdm_rotation` function and for reporting the bug! I was wondering whether someone finds the new function useful and if it even works (I personally use qpAdm only very rarely and have not tested it enough as a result)! Well, clearly it doesn't. :) I really appreciate your careful examination of the problem and debugging!

I'm currently very busy with some unpleasant deadlines and likely will be for the next 1-2 weeks. Not sure if I will have enough time to implement a fix and test it until then.

It appears though as if you might have found a solution? If so, would you be interested in submitting a pull request with the fix? It would be extremely helpful and would speed things up significantly. Of course, you would be properly acknowledged in the changelog on the _admixr_ website!

It's OK if you can't/don't want to do this though. In that case, I would take a look at things properly in that 1-2 week timeframe.

Thank you again!

**Comment by bodkan** [comment] 2022-08-01 20:28
My goodness. _"1-2 week timeframe"_, he said.

Different. country. Different job. Different life. Still, better late than never I guess!

I'm pretty sure you've moved on and perhaps even fixed the problem yourself. In any case, thanks to your input, the issue is now fixed.

What's even funnier, given how long this all took, is that the fix didn't take more than 2 hours to implement, including new unit tests. Oh well.

Closing now. Fix will be added to version 1.0 that's going to be submitted to CRAN once other bugfixes are implemented.

**Closed as completed by bodkan** 2022-08-01 20:28 UTC
