### ISSUE TITLE
issue with filter_bed: Inconsistent naming convention

### ISSUE THREAD

**Issue by mgb1985** [bodkan/admixr#72] opened 2020-08-25 16:19 UTC
Hi!

Thanks for the package, it is super easy to use!
I have an issue though:

I wanted to filter out some SNPs using:
```
bed <- file.path(dirname(prefix), "myregions.bed")
snps_Run3b <- filter_bed(snps_Run3, bed, remove = TRUE)
```

Unfortunately, I'm not working on humans, neither I have a perfect chromosome-level genome, so that my contigs have unconventional names.
In bedtools, one can use the option -nonamecheck to force the software despite unconventional naming.

Seems like filter_bed in R doesn't allow that?
I have  an object created but it says:
```
modifiers:
  groups:  <path> 
  excluded sites:  <path_to file.snp> 
      (SNPs excluded: 0, SNPs remaining: 5133074)
```

Any advice on that?

Thanks!

M

**Comment by bodkan** [comment] 2020-08-28 10:49
Hi, thank you for being interested in the package!

I apologize for not being non-human friendly enough. I have to admit that I mostly work with human data...

I'm not deeply familar with `-nonamecheck` - is this something that could be simply turned on by default? I'm happy to do that as long is it doesn't break things in other cases. Do you have an opinion on that?

Looking at the code of the function [here](https://github.com/bodkan/admixr/blob/323f3956fa817026cb609c1b1e79f8cb4c9e0a89/R/eigenstrat.R#L173), I see that the intersect is not running with the `-sorted` option by default. I wonder if that should be also turned on while we're at it...? 🤔 

Either way, I'm happy to implement a quick fix, even turning it on by default. Let me know what you think!

**Comment by mgb1985** [comment] 2020-09-11 11:52
Hi  Bodkan!

Thanks for your email and sorry for the late reply!

No worries for the non-human friendly issue, we are used to it, and at least you are proposing solutions!

From what I know, the `-nonamecheck` just force the software to work without checking the name. I don't think it is making any other trouble but I cannot guarantee 200%.

As per the `-sorted` option, I don't see a necessity nor an issue in turning it on!

Thanks!

M

**Comment by bodkan** [comment] 2020-09-11 14:07
Hi again,

Thanks for the reply. I just created a [testing branch](https://github.com/bodkan/admixr/tree/bedtools-nonamecheck) where I will add both `-nonamecheck` and `-sorted`. I will run unit tests on TravisCI and see if it blows up. If it doesn't, I would push the change to the main branch.

Thank you for being patient.

**Comment by bodkan** [comment] 2020-09-11 20:57
Hey @mgb1985,

Would you mind running `devtools::install_github("bodkan/admixr", ref = "bedtools-nonamecheck")` to get the development version with `-nonamecheck` implementent and test if your code works now? I'm not entirely sure how to check this properly as I don't have a suitable testing dataset available. The Travis CI unit tests passed without problems though...

Don't worry about breaking other things, if the code doesn't work, you can always revert back to the latest stable version with `install.packages("admixr")`.

Thanks for your help!

**Comment by mgb1985** [comment] 2020-10-05 11:24
Hi @bodkan!

Sorry for the very late reply! 

I installed the dev version as you said, which gave a `DONE` status.
I then tried to filter my dataset, but got the same issue (bed has inconsistent naming convention).
But when I look at the code of the `filter_bed` function, I don't see the implementation of the nonamecheck option.
So I'm wondering if I installed the dev version properly.
Is there something I should do after `devtools::install_github("bodkan/admixr", ref = "bedtools-nonamecheck")`?

Thanks!

**Comment by bodkan** [comment] 2020-10-06 12:14
Hello again!

This is strange. Can you paste here what you get by simply typing `filter_bed` in your R console after running `library(admixr`) after you did the installation? So, pasting the code itself.

I admit I did the fix quite in haste (currently in the last stages of submitting my thesis, finally) so I fully accept the possibility that I messed up. It could also be that I still don't fully understand what bedtools does here (I did not yet have time to test this on some real data, or at least fake real data that I should generate for a unit test later).

Sorry this is still giving you trouble!

**Comment by murielgb** [comment] 2020-10-07 10:51
Hi Peter!

Here is the code of filter_bed, after doing `library(admixr)`:
```
function (data, bed, remove = FALSE, outfile = tempfile(fileext = ".snp")) 
{
    if (file.exists(outfile)) {
        warning(paste("snp file", outfile, "already exists - adding it to the EIGENSTRAT object directly."), 
            call. = FALSE)
        data <- add_excluded_snps(data, outfile)
        return(data)
    }
    if (Sys.which("bedtools") == "") 
        stop("bedtools is required for filtering, but is not in your $PATH")
    if (!file.exists(bed)) 
        stop("BED file '", bed, "' not found", call. = FALSE)
    snp <- read_snp(data)
    tmpbed <- tempfile()
    snp %>% dplyr::mutate(start = pos - 1, end = pos) %>% dplyr::select(chrom, 
        start, pos) %>% readr::write_tsv(tmpbed, col_names = FALSE)
    output <- tempfile()
    sprintf("bedtools intersect %s -c -a %s -b %s > %s", ifelse(remove, 
        "-v", ""), tmpbed, bed, output) %>% system()
    snp_hits <- readr::read_tsv(output, col_names = c("chrom", 
        "start", "end", "hit"), col_types = "ciii", progress = FALSE)
    exclude <- snp[snp_hits$hit == as.integer(remove), ]
    data <- process_filter(data, exclude, outfile)
    data
}
<bytecode: 0x11e3ae2d0>
<environment: namespace:admixr>
```

And same after running `devtools::install_github("bodkan/admixr", ref = "bedtools-nonamecheck"):`
```
function (data, bed, remove = FALSE, outfile = tempfile(fileext = ".snp")) 
{
    if (file.exists(outfile)) {
        warning(paste("snp file", outfile, "already exists - adding it to the EIGENSTRAT object directly."), 
            call. = FALSE)
        data <- add_excluded_snps(data, outfile)
        return(data)
    }
    if (Sys.which("bedtools") == "") 
        stop("bedtools is required for filtering, but is not in your $PATH")
    if (!file.exists(bed)) 
        stop("BED file '", bed, "' not found", call. = FALSE)
    snp <- read_snp(data)
    tmpbed <- tempfile()
    snp %>% dplyr::mutate(start = pos - 1, end = pos) %>% dplyr::select(chrom, 
        start, pos) %>% readr::write_tsv(tmpbed, col_names = FALSE)
    output <- tempfile()
    sprintf("bedtools intersect %s -c -a %s -b %s > %s", ifelse(remove, 
        "-v", ""), tmpbed, bed, output) %>% system()
    snp_hits <- readr::read_tsv(output, col_names = c("chrom", 
        "start", "end", "hit"), col_types = "ciii", progress = FALSE)
    exclude <- snp[snp_hits$hit == as.integer(remove), ]
    data <- process_filter(data, exclude, outfile)
    data
}
<bytecode: 0x11e3ae2d0>
<environment: namespace:admixr>
```

Don't worry too much on this issue now while you are writing your thesis!!
In the end, I generated a new bed file without the region outside or R.
Of course it would be better that it works directly in, and as you said I won't be the only one who wants to use the package but works on non-human models, but nothing urgent here!!

Thanks a lot!

Muriel

**Comment by bodkan** [comment] 2022-08-02 12:40
So, it's been a while. Embarrassingly long while! But here we are, closing issues accumulated over the last 1-2 years. This is the last of them.

# Short story

`filter_bed()` now has an optional argument `bedtools_args = ""` where optional arguments that should be passed to `bedtools intersect` can be provided. In this context, specifying `filter_bed(..., bedtools_args = "-nonamecheck")` does what was requested. However, the matter seems/seemed to be a bit more complicated, see below if you run into the same problem, dear future user.

# Long story

After trying to Google around bedtools `-nonamecheck` options and making lots of fake testing data, I have to say I'm still a bit confused with when exactly is this a problem. (Again, having unfortunately no practical experience with situations when `-nonamecheck` is needed in my own work.)

Consider this example:

Load example data from the internet:

```
library(admixr)
data <- eigenstrat(download_data())
```

## Case # 1 

Create a BED file of 10 positions, 5 with weird chromosome/contig names, 5 with names corresponding to what is in `data`:

```
bed_file <- tempfile()
modified_snp <- tempfile()
read_snp(data) %>%
  dplyr::sample_n(10) %>%
  dplyr::arrange(chrom, pos) %>%
  dplyr::mutate(chrom = c(chrom[1:5], paste0("asdfchr", chrom[6:10]))) %>%
  write_snp(modified_snp)
snp_to_bed(modified_snp, bed_file)
```

This is what that BED file contains:

```
> readr::read_tsv(bed_file, col_names = c("chrom", "start", "end"), show_col_types = FALSE)
                                                                                                        # A tibble: 10 × 3
   chrom        start       end
   <chr>        <dbl>     <dbl>
 1 1        116324701 116324702
 2 12        63870587  63870588
 3 16        26530158  26530159
 4 16        86069788  86069789
 5 18        74746541  74746542
 6 asdfchr3  73260999  73261000
 7 asdfchr3 100614558 100614559
 8 asdfchr6  50925209  50925210
 9 asdfchr7 145195524 145195525
10 asdfchr8  88329944  88329945
```

When I use this BED file for filtering (first message of this issue thread), I get no problem. 5 positions which correspond to what's in the data get removed, the remaining 5 with weird contig names are ignored. bedtools gives no error or warning:

```
> filter_bed(data, bed_file, remove = TRUE)
EIGENSTRAT object                                                             
=================
components:
  ind file: /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/snps/snps.ind
  snp file: /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/snps/snps.snp
  geno file: /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/snps/snps.geno

modifiers:
  excluded sites:  /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/file6adda365ba3.snp 
      (SNPs excluded: 5, SNPs remaining: 499995)
```

Unless I'm missing something obvious, the bedtools warning reported at the beginning of this thread should not make `filter_bed()` miss filtering some sites.

## Case # 2

Let's create a different BED file, this time adding a `chr` prefix to 5 positions (remaining 5 positions correspond exactly some that are in the `data`):

```
  bed_file <- tempfile()
  modified_snp <- tempfile()
  read_snp(data) %>%
    dplyr::sample_n(10) %>%
    dplyr::arrange(chrom, pos) %>%
    dplyr::mutate(chrom = c(chrom[1:5], paste0("chr", chrom[6:10]))) %>%
    write_snp(modified_snp)
  snp_to_bed(modified_snp, bed_file)
```

This is what the BED file contains:

```
> readr::read_tsv(bed_file, col_names = c("chrom", "start", "end"), show_col_types = FALSE)
                                                                                                        # A tibble: 10 × 3
   chrom     start       end
   <chr>     <dbl>     <dbl>
 1 11     39346555  39346556
 2 11     44725547  44725548
 3 14    101936767 101936768
 4 18     38655421  38655422
 5 18     75430547  75430548
 6 chr2   37908979  37908980
 7 chr3  100203536 100203537
 8 chr4  151773021 151773022
 9 chr5   32114369  32114370
10 chr5  167863192 167863193
```

Now when we run `filter_bed()` again, we get a warning from bedtools. **However, the data is still filtered correctly!** This seems that the original error reported in this issue isn't caused by strange contigs? 🤔 

```
> filter_bed(data, bed_file, remove = TRUE)
***** WARNING: File /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/file6add56e19d66 has inconsistent naming convention for record:
chr2    37908979        37908980

***** WARNING: File /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/file6add56e19d66 has inconsistent naming convention for record:
chr2    37908979        37908980

EIGENSTRAT object                                                             
=================
components:
  ind file: /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/snps/snps.ind
  snp file: /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/snps/snps.snp
  geno file: /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/snps/snps.geno

modifiers:
  excluded sites:  /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/file6add66bfe5e7.snp 
      (SNPs excluded: 5, SNPs remaining: 499995)
```


Running `filter_bed()` with the new `bedtools_args = "-nonamecheck"` works, but merely silences the warning. The filtering proceeds in a standard way and the result is the same as what happens above without `-nonamecheck` in place:

```
> filter_bed(data, bed_file, remove = TRUE, bedtools_args = "-nonamecheck")
EIGENSTRAT object                                                             
=================
components:
  ind file: /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/snps/snps.ind
  snp file: /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/snps/snps.snp
  geno file: /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/snps/snps.geno

modifiers:
  excluded sites:  /var/folders/d_/hblb15pd3b94rg0v35920wd80000gn/T//Rtmprebxmd/file6add6d9bcd60.snp 
      (SNPs excluded: 5, SNPs remaining: 499995)
```

----

This makes me thing that the original error was possibly caused by something else? I know very little about the motivation behind `-nonamecheck` but it doesn't look like it should protect against "unconventional names of chromosomes/contigs" as originally reported. Given that the warning is triggered when `chr` prefix is added to a numerical chromosome name, it seems that it should protect/warn against different reference genomes used, or something like that?

----

Either way, the `bedtools_args = ` is useful at least because it allows `bedtools_args = "-sorted"`, switching on faster intersection on properly sorted BED files.

----

### Please reopen if a related (or the same!) issue comes up

**Closed as completed** 2022-08-02 12:40 UTC
